.TH "OTBconfigGUI/include/mainwindow.h" 3 "Fri May 10 2019" "lslpub_OTB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OTBconfigGUI/include/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBACQ_SETT\fP   0b10000000"
.br
.ti -1c
.RI "#define \fBDECIM\fP   0b01000000"
.br
.ti -1c
.RI "#define \fBREC_ON\fP   0b00100000"
.br
.ti -1c
.RI "#define \fBFSAMP1\fP   0b00010000"
.br
.ti -1c
.RI "#define \fBFSAMP0\fP   0b00001000"
.br
.ti -1c
.RI "#define \fBNCH1\fP   0b00000100"
.br
.ti -1c
.RI "#define \fBNCH0\fP   0b00000010"
.br
.ti -1c
.RI "#define \fBACQ_ON\fP   0b00000001"
.br
.ti -1c
.RI "#define \fBACQ_OFF\fP   0b00000000"
.br
.ti -1c
.RI "#define \fBCRC_CODE\fP   0b10001100"
.br
.ti -1c
.RI "#define \fBCONFIG_SIZE\fP   40"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ACQ_OFF   0b00000000"

.SS "#define ACQ_ON   0b00000001"

.SS "#define ACQ_SETT   0b10000000"

.SS "#define CONFIG_SIZE   40"

.SS "#define CRC_CODE   0b10001100"

.SS "#define DECIM   0b01000000"

.SS "#define FSAMP0   0b00001000"

.SS "#define FSAMP1   0b00010000"

.SS "#define NCH0   0b00000010"

.SS "#define NCH1   0b00000100"

.SS "#define REC_ON   0b00100000"

.SH "Author"
.PP 
Generated automatically by Doxygen for lslpub_OTB from the source code\&.
