.TH "Ui::MainWindow" 3 "Fri May 10 2019" "lslpub_OTB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_mainwindow\&.h>\fP
.PP
Inherits \fBUi_MainWindow\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for lslpub_OTB from the source code\&.
